# -*- coding: utf-8 -*-
# Eigrutel Lab / Atelier d'outils libres pour la bande dessinée
# Programme conçu et développé par Simon Léturgie
# dans le cadre d'Eigrutel BD Academy.
# Nom public : Morgue
# Version : 3.1.12
# Date : 10-09-2026
# Application de bureau : sources Python (.py) et exécutable Windows (.exe).
# Code source et programme compilé : GNU AGPL v3.0 ou version ultérieure.
# Documentation et ressources : CC BY-SA 4.0, sauf mention contraire.
# Les bibliothèques tierces conservent leurs licences respectives.
# Marques, logos et signes distinctifs Eigrutel / Eigrutel Lab /
# Eigrutel BD Academy : réservés.

# English naming template recovered from the earlier Morgue Renamer.
STRUCTURE_EN = {'Animals': {'Horses': ['Ranch_Western', 'Work', 'Trot_Race_Jump'],
             'Misc': ['Insects', 'Birds', 'Fish', 'Reptiles'],
             'Domestic': ['Cattle', 'Cats', 'Dogs', 'Rabbits', 'Sheep', 'Pigs', 'Rodents'],
             'Wild': ['Deer', 'Camels', 'Elephants', 'Felines', 'Wolves', 'Bears', 'Foxes', 'Monkeys']},
 'Arts_and_Sciences': {'Arts': ['Composition', 'Colors', 'Sculpture'],
                       'Sciences': ['Astronomy', 'Laboratory', 'Medical']},
 'Costume': {'Misc': ['Armor', 'Military', 'Nobility', 'Theater', 'Uniforms'],
             'Period': ['15th', '16th', '17th', '18th', '19th', '20th', 'Antiquity', 'Middle_Ages'],
             'Children_Fashion': ['Jewelry',
                                  'Hats',
                                  'Shoes',
                                  'Shirts',
                                  'Hair',
                                  'Costumes',
                                  'Lingerie',
                                  'Glasses',
                                  'Coats',
                                  'Pants',
                                  'Sweaters',
                                  'Pajamas'],
             'Women_Fashion': ['Jewelry',
                               'Hats',
                               'Shoes',
                               'Shirts',
                               'Hair',
                               'Costumes',
                               'Furs',
                               'Lingerie',
                               'Glasses',
                               'Coats',
                               'Pants',
                               'Sweaters',
                               'Pajamas'],
             'Men_Fashion': ['Hats',
                             'Shoes',
                             'Shirts',
                             'Hair',
                             'Costumes',
                             'Lingerie',
                             'Glasses',
                             'Coats',
                             'Pants',
                             'Sweaters',
                             'Pajamas'],
             'Fabrics': ['Flags', 'Patterns', 'Folds', 'Textures']},
 'Misc': {'Disasters': ['Explosions', 'Fires', 'Floods', 'Storms'],
          'General': ['War', 'Newspapers', 'Food', 'Telephones', 'Holidays'],
          'School': ['Middle_School', 'College', 'High_School', 'Kindergarten', 'Primary_School'],
          'State': ['Government', 'Police', 'Post_Office', 'Prison'],
          'Religious': ['Shamanism', 'Christians', 'Hindus', 'Jews', 'Weddings', 'Muslims'],
          'Street': ['Streetlights_Lighting', 'Bridges', 'Street_Scenes', 'Tunnels']},
 'Entertainment': {'Cinema': ['Camera_Equipment', 'Sets', 'Theater'],
                   'Dance': ['Ballet', 'HipHop', 'Studio'],
                   'Misc': ['Carnivals',
                            'Circuses',
                            'Nightclubs',
                            'Parties',
                            'Radio',
                            'Restaurants',
                            'Television'],
                   'Video_Games': ['FPS_FirstPersonShooter', 'Gaming', 'PixelArt', 'Platformers'],
                   'Music': ['Singers', 'Concerts', 'Strings', 'Orchestra', 'Percussion', 'Winds'],
                   'Theater': ['Backstage', 'Hall', 'Stage']},
 'Geography': {'Africa': ['Central', 'Egypt', 'East', 'Maghreb', 'West', 'South'],
               'Central_South_America': ['Amazon', 'Brazil', 'Caribbean', 'Mexico', 'Peru'],
               'North_America': ['California',
                                 'Canada',
                                 'East',
                                 'Florida',
                                 'Midwest',
                                 'NewYork',
                                 'South',
                                 'WashingtonDC',
                                 'West'],
               'Asia': ['China', 'Korea', 'India', 'Japan', 'Vietnam'],
               'Europe': ['Germany',
                          'England',
                          'Balkans',
                          'Spain',
                          'France',
                          'Italy',
                          'Eastern_Europe',
                          'Russia',
                          'Scandinavia'],
               'Oceania': ['Australia', 'New_Zealand']},
 'Industry': {'Agriculture': ['Farm_Equipment', 'Farms', 'Barns'],
              'Industry': ['Steel',
                           'Food',
                           'Wood',
                           'Chemicals',
                           'Construction',
                           'Mines',
                           'Oil',
                           'Factories'],
              'Shops_Offices': ['Food',
                                'Butcher_Shops',
                                'Bakeries',
                                'Banks',
                                'Various_Shops',
                                'Offices',
                                'Grocery_Stores',
                                'Pharmacies']},
 'Housing': {'Exterior': ['Fences_Walls',
                          'Stairs',
                          'Facades',
                          'Garages',
                          'Gates',
                          'Porches_Terraces',
                          'Doors_Windows'],
             'Interior': ['Studios',
                          'Laundry',
                          'Heating_Ventilation',
                          'Fireplaces',
                          'Stairs',
                          'Walls',
                          'Doors_Windows'],
             'Furniture': ['Silverware',
                           'Bar',
                           'Screens',
                           'Clocks',
                           'Lamps',
                           'Mirrors_Frames',
                           'Tableware',
                           'Desks',
                           'Sofas',
                           'Chairs',
                           'Dressers_Wardrobes',
                           'Outdoor_Furniture',
                           'Tables'],
             'Rooms': ['Bedrooms', 'Kitchens', 'Dining_Rooms', 'Bathrooms', 'Living_Rooms', 'Toilets']},
 'Nature': {'Trees': ['With_Leaves', 'Bare_Branches', 'Blossom', 'Trunks_Bark', 'Tropics'],
            'Misc': ['Lightning', 'Mountains', 'Clouds', 'Rocks'],
            'Gardens_Flowers': ['Garden_Accessories',
                                'Flowers',
                                'Gardens',
                                'Garden_Tools',
                                'Plants',
                                'Vines'],
            'Snow_Water': ['Water', 'Ice', 'Snow']},
 'People': {'Misc': ['Celebrities', 'Crowds'],
            'Children': ['Teenagers',
                         'Playgrounds',
                         'Babies',
                         'Girls',
                         'Boys',
                         'Toys',
                         'Children_Bedroom_Furniture'],
            'Women': ['Angle',
                      'Emotions_Expressions',
                      'Mature',
                      'Nudes',
                      'Seated_Model',
                      'Standing_Model',
                      'Floor_Model',
                      'Profile',
                      'Old',
                      'Full_Face'],
            'Men': ['Angle',
                    'Beards',
                    'Tough_Guys',
                    'Emotions_Expressions',
                    'Mature',
                    'Nudes',
                    'Seated_Model',
                    'Standing_Model',
                    'Floor_Model',
                    'Profile',
                    'Old',
                    'Full_Face']},
 'Sports': {'Events': ['Baseball',
                       'Basketball',
                       'Boxing',
                       'Car_Racing',
                       'Football',
                       'Hockey',
                       'Track',
                       'Bullfighting'],
            'Individual': ['Bowling',
                           'Camp_Picnic',
                           'Cycling',
                           'Golf',
                           'Gym',
                           'Swimming',
                           'Fishing',
                           'Skiing',
                           'Winter_Sports',
                           'Tennis',
                           'Shooting',
                           'Archery']},
 'Transport': {'Cars': ['Vintage', 'Vans', 'Trucks', 'Motorcycles', 'Trailers', 'Gas_Stations', 'Urban'],
               'Aircraft': ['Planes', 'Airliners', 'Helicopters', 'Parachutes'],
               'Boats': ['Rowboats', 'Canoes', 'Cruises', 'Cargo_Ships', 'Liners', 'Sailboats'],
               'Public': ['Luggage', 'Buses', 'Stations', 'Taxis', 'Trains']},
 'References': {'Comics': ['Franco_Belgian', 'Comics_US', 'Manga', 'Author'],
                'Animation': ['Character', 'Background', 'Disney', 'Stopmotion'],
                'Illustration': ['Painting', 'Cover', 'Black_and_White', 'Poster']}}
